# Configuration
defaultContentLanguage = "en"
sectionPagesMenu = "main"

[params.About]
title = "Nino"
author = "takai24"
description = "hi."
source = "https://github.com/takai24"
baseURL = "https://takai24.github.io"
imageURL = "/assets/index.png"

[params.Theme]
themeColor = "#000000"