# Configuration
defaultContentLanguage = "en"
sectionPagesMenu = "main"

[params.About]
title = "Ducc"
author = "itsccao"
description = "Hi, I'm Ducc."
source = "https://github.com/itsccao"
baseURL = "https://itsccao.github.io"
imageURL = "/assets/index.png"

[params.Theme]
themeColor = "#000000"